FROM ubuntu:20.04
WORKDIR /usr/app/
COPY ./nginx ./nginx

RUN apt update

RUN apt install -y --no-install-recommends nginx

CMD ["nginx", "-c", "/usr/app/nginx/nginx.docker.conf", "-g", "daemon off;"]
